### ISSUE TITLE
[BUG]: Migrate getDatasetFromFile endpoint to SST

### ISSUE THREAD

**Issue by noah-iversen** [DSGT-DLP/Deep-Learning-Playground#980]
### Operating system

Windows 11

### Bug description

When a user attempts to train under tabular and uploads their own file, there used to be an endpoint that could be called to parse the uploaded file. 

However, we are migrating our endpoints to SST and the one that handles reading the dataset has not been migrated yet. Your task is to migrate the endpoint called getDatasetFromFile to SST and make necessary changes in the transpaceApi.ts file.

Default endpoint url: ``/api/training/datasets/default/${dataset.name}/columns``
getDatasetFromFile url: ``/api/dataset/getColumnsFromDatasetFile``

Beware: "getColumnsFromDataset" and getColumnsFromDatasetFile" are different names to refer to. The former is the name of the RTK query itself, and the latter is the appended name to the endpoint URL.

When calling to the endpoint, either the default endpoint or the "getDatasetFromFile" gets appended. Ensure that the new appended url is accurate when making these changes. 

The only changes necessary should be to the getDatasetFromFile URL itself, since it's a GET call.

### Steps to reproduce

https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/7332345/37031dbb-6ee8-453b-bc4e-9e1bd72cc17b

Visit trainspace, go under tabular, upload file, and then view the error that occurs due to the invalid endpoint call. See video.

**Comment by karkir0003** [comment]
@noah-iversen Below would be the general steps to migrate `getDatasetFromFile` endpoint to SST (the endpoint responsible for getting columns from user uploaded CSV file):

Links to the original code: [`getColumnsFromDatasetFile`](https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/f3c7cd51a1f38b786a1ccab7b00212833641abe3/backend/endpoints/dataset_endpoints.py#L43-L71), [`get_column_names(}`](https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/f3c7cd51a1f38b786a1ccab7b00212833641abe3/backend/aws_helpers/s3_utils/s3_client.py#L172-L188)

1. It turns out that the endpoint reponsible for extracting columns from user uploaded CSV lives [here](https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/f3c7cd51a1f38b786a1ccab7b00212833641abe3/serverless/packages/functions/src/datasets/user/columns.ts)
2. All you need to do is modify the URL used [here](https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/nextjs/frontend/src/features/Train/redux/trainspaceApi.ts#L81) to point to the route shown [here](https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/f3c7cd51a1f38b786a1ccab7b00212833641abe3/serverless/stacks/AppStack.ts#L36). This should be similar approach to your previous [PR](https://github.com/DSGT-DLP/Deep-Learning-Playground/pull/978)

**Comment by karkir0003** [comment]
@noah-iversen status on this task?
